{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapdeck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapdeck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapdeck/mapdeck_{{ version }}.tar.gz
  sha256: 82b93da4b1118496d3e0dfaccaad415335350b0871d1f6fdf195e2324173e39f

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-colourvalues >=0.3.4
    - r-geojsonsf >=1.3.3
    - r-geometries
    - r-googlepolylines >=0.7.2
    - r-htmlwidgets
    - r-jsonify >=1.1.1
    - r-magrittr
    - r-rapidjsonr
    - r-sfheaders >=0.2.2
    - r-shiny
    - r-spatialwidget >=0.2.3
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-colourvalues >=0.3.4
    - r-geojsonsf >=1.3.3
    - r-geometries
    - r-googlepolylines >=0.7.2
    - r-htmlwidgets
    - r-jsonify >=1.1.1
    - r-magrittr
    - r-rapidjsonr
    - r-sfheaders >=0.2.2
    - r-shiny
    - r-spatialwidget >=0.2.3

test:
  commands:
    - $R -e "library('mapdeck')"           # [not win]
    - "\"%R%\" -e \"library('mapdeck')\""  # [win]

about:
  home: https://symbolixau.github.io/mapdeck/articles/mapdeck.html
  dev_url: https://github.com/SymbolixAU/mapdeck
  license: GPL-3.0-only
  summary: Provides a mechanism to plot an interactive map using 'Mapbox GL' (<https://www.mapbox.com/mapbox-gl-js/api/>), a javascript library for interactive maps, and 'Deck.gl' (<http://deck.gl/#/>), a javascript library which uses 'WebGL' for visualising large data sets.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
