{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mapdeck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapdeck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapdeck/mapdeck_{{ version }}.tar.gz
  sha256: 82b93da4b1118496d3e0dfaccaad415335350b0871d1f6fdf195e2324173e39f

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bh                         # [build_platform != target_platform]
    - r-colourvalues               # [build_platform != target_platform]
    - r-geojsonsf                  # [build_platform != target_platform]
    - r-geometries                 # [build_platform != target_platform]
    - r-googlepolylines            # [build_platform != target_platform]
    - r-htmlwidgets                # [build_platform != target_platform]
    - r-interleave                 # [build_platform != target_platform]
    - r-jsonify                    # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
    - r-rapidjsonr                 # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-sfheaders                  # [build_platform != target_platform]
    - r-shiny                      # [build_platform != target_platform]
    - r-spatialwidget              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-colourvalues >=0.3.9
    - r-geojsonsf >=2.0.3
    - r-geometries >=0.2.4
    - r-googlepolylines >=0.7.2
    - r-htmlwidgets
    - r-interleave >=0.1.2
    - r-jsonify >=1.2.2
    - r-magrittr
    - r-rapidjsonr
    - r-rcpp >=1.0.10
    - r-sfheaders >=0.4.4
    - r-shiny
    - r-spatialwidget >=0.2.5
  run:
    - r-base
    - r-colourvalues >=0.3.9
    - r-geojsonsf >=2.0.3
    - r-googlepolylines >=0.7.2
    - r-htmlwidgets
    - r-jsonify >=1.2.2
    - r-magrittr
    - r-rcpp >=1.0.10
    - r-sfheaders >=0.4.4
    - r-shiny

test:
  commands:
    - $R -e "library('mapdeck')"           # [not win]
    - "\"%R%\" -e \"library('mapdeck')\""  # [win]

about:
  home: https://symbolixau.github.io/mapdeck/articles/mapdeck.html
  dev_url: https://github.com/SymbolixAU/mapdeck
  license: GPL-3.0-only
  summary: Provides a mechanism to plot an interactive map using 'Mapbox GL' (<https://www.mapbox.com/mapbox-gl-js/api/>), a javascript library for interactive maps, and 'Deck.gl' (<http://deck.gl/#/>), a javascript library which uses 'WebGL' for visualising large data sets.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
